import { Factory, Seeder } from 'typeorm-seeding';
import { Connection } from 'typeorm';
import { UsersEntity } from '../../entity/';

export default class CreateUsers implements Seeder {
  public async run(factory: Factory, connection: Connection): Promise<any> {
    const current = new Date();
    const firstThisWeek = current.getDate() - current.getDay() + 1;
    const users = [
      {
        id: 1,
        name: 'name user 1',
        description: 'user 1',
        email: 'user1@gmail.com',
        address: '0xe42b1f6be2ddb834615943f2b41242b172788e7e',
        pubkey:
          '0x032c44efc5533ff7f9f5d9edb49f8075b210f1cb5ca414f947ecaa22fa4caeca01',
        username: '1',
        profileImg: 'https://picsum.photos/1000',
        nonce: 0,
        createdAt: new Date(current.setDate(firstThisWeek - 7)).toISOString(),
        updatedAt: new Date(current.setDate(firstThisWeek - 7)).toISOString(),
      },
      {
        id: 2,
        name: 'name user 2',
        description: 'user 2',
        email: 'user2@gmail.com',
        address: '0x6538727503807d36d593d8b2d7aa70b22fe0f460',
        pubkey:
          '0x02d26f7738eb1449acc9c2da7dbd83f2a63fb7995978e895e1897937bfc49be71d',
        username: '2',
        profileImg: 'https://picsum.photos/1000',
        nonce: 0,
        createdAt: new Date(current.setDate(firstThisWeek - 6)).toISOString(),
        updatedAt: new Date(current.setDate(firstThisWeek - 6)).toISOString(),
      },
      {
        id: 3,
        name: 'name user 3',
        description: 'user 3',
        email: 'user3@gmail.com',
        address: '0x3',
        pubkey: '0x3',
        username: '3',
        profileImg: 'https://picsum.photos/1000',
        nonce: 0,
        createdAt: new Date(current.setDate(firstThisWeek - 6)).toISOString(),
        updatedAt: new Date(current.setDate(firstThisWeek - 6)).toISOString(),
      },
      {
        id: 4,
        name: 'name user 4',
        description: 'user 4',
        email: 'user4@gmail.com',
        address: '0x4',
        pubkey: '0x4',
        username: '4',
        profileImg: 'https://picsum.photos/1000',
        nonce: 0,
        createdAt: new Date(current.setDate(firstThisWeek - 5)).toISOString(),
        updatedAt: new Date(current.setDate(firstThisWeek - 5)).toISOString(),
      },
      {
        id: 5,
        name: 'name user 5',
        description: 'user 5',
        email: 'user5@gmail.com',
        address: '0x5',
        pubkey: '0x5',
        username: '5',
        profileImg: 'https://picsum.photos/1000',
        nonce: 0,
        createdAt: new Date(current.setDate(firstThisWeek - 5)).toISOString(),
        updatedAt: new Date(current.setDate(firstThisWeek - 5)).toISOString(),
      },
      {
        id: 6,
        name: 'name user 6',
        description: 'user 6',
        email: 'user6@gmail.com',
        address: '0x6',
        pubkey: '0x6',
        username: '6',
        profileImg: 'https://picsum.photos/1000',
        nonce: 0,
        createdAt: new Date(current.setDate(firstThisWeek - 5)).toISOString(),
        updatedAt: new Date(current.setDate(firstThisWeek - 5)).toISOString(),
      },
      {
        id: 7,
        name: 'name user 7',
        description: 'user 7',
        email: 'user7@gmail.com',
        address: '0x7',
        pubkey: '0x7',
        username: '7',
        profileImg: 'https://picsum.photos/1000',
        nonce: 0,
        createdAt: new Date(current.setDate(firstThisWeek - 4)).toISOString(),
        updatedAt: new Date(current.setDate(firstThisWeek - 4)).toISOString(),
      },
      {
        id: 8,
        name: 'name user 8',
        description: 'user 8',
        email: 'user8@gmail.com',
        address: '0x8',
        pubkey: '0x8',
        username: '8',
        profileImg: 'https://picsum.photos/1000',
        nonce: 0,
        createdAt: new Date(current.setDate(firstThisWeek - 3)).toISOString(),
        updatedAt: new Date(current.setDate(firstThisWeek - 3)).toISOString(),
      },
      {
        id: 9,
        name: 'name user 9',
        description: 'user 9',
        email: 'user9@gmail.com',
        address: '0x9',
        pubkey: '0x9',
        username: '9',
        profileImg: 'https://picsum.photos/1000',
        nonce: 0,
        createdAt: new Date(current.setDate(firstThisWeek - 3)).toISOString(),
        updatedAt: new Date(current.setDate(firstThisWeek - 3)).toISOString(),
      },
      {
        id: 10,
        name: 'name user 10',
        description: 'user 10',
        email: 'user10@gmail.com',
        address: '0x10',
        pubkey: '0x10',
        username: '10',
        profileImg: 'https://picsum.photos/1000',
        nonce: 0,
        createdAt: new Date(current.setDate(firstThisWeek)).toISOString(),
        updatedAt: new Date(current.setDate(firstThisWeek)).toISOString(),
      },
      {
        id: 11,
        name: 'name user 11',
        description: 'user 11',
        email: 'user11@gmail.com',
        address: '0x11',
        pubkey: '0x111',
        username: '11',
        profileImg: 'https://picsum.photos/1000',
        nonce: 0,
        createdAt: new Date(current.setDate(firstThisWeek)).toISOString(),
        updatedAt: new Date(current.setDate(firstThisWeek)).toISOString(),
      },
      {
        id: 12,
        name: 'name user 12',
        description: 'user 12',
        email: 'user12@gmail.com',
        address: '0x12',
        pubkey: '0x12',
        username: '12',
        profileImg: 'https://picsum.photos/1000',
        nonce: 0,
        createdAt: new Date(current.setDate(firstThisWeek + 1)).toISOString(),
        updatedAt: new Date(current.setDate(firstThisWeek + 1)).toISOString(),
      },
      {
        id: 13,
        name: 'name user 13',
        description: 'user 13',
        email: 'user13@gmail.com',
        address: '0x13',
        pubkey: '0x13',
        username: '13',
        profileImg: 'https://picsum.photos/1000',
        nonce: 0,
        createdAt: new Date(current.setDate(firstThisWeek + 2)).toISOString(),
        updatedAt: new Date(current.setDate(firstThisWeek + 2)).toISOString(),
      },
      {
        id: 14,
        name: 'name user 14',
        description: 'user 14',
        email: 'user14@gmail.com',
        address: '0x14',
        pubkey: '0x14',
        username: '14',
        profileImg: 'https://picsum.photos/1000',
        nonce: 0,
        createdAt: new Date(current.setDate(firstThisWeek + 2)).toISOString(),
        updatedAt: new Date(current.setDate(firstThisWeek + 2)).toISOString(),
      },
      {
        id: 15,
        name: 'name user 15',
        description: 'user 15',
        email: 'user15@gmail.com',
        address: '0x15',
        pubkey: '0x15',
        username: '15',
        profileImg: 'https://picsum.photos/1000',
        nonce: 0,
        createdAt: new Date(current.setDate(firstThisWeek + 2)).toISOString(),
        updatedAt: new Date(current.setDate(firstThisWeek + 2)).toISOString(),
      },
      {
        id: 16,
        name: 'name user 16',
        description: 'user 16',
        email: 'user16@gmail.com',
        address: '0x16',
        pubkey: '0x16',
        username: '16',
        profileImg: 'https://picsum.photos/1000',
        nonce: 0,
        createdAt: new Date(current.setDate(firstThisWeek + 3)).toISOString(),
        updatedAt: new Date(current.setDate(firstThisWeek + 3)).toISOString(),
      },
    ];
    await connection
      .createQueryBuilder()
      .insert()
      .into(UsersEntity)
      .values(users)
      .execute();
  }
}
